/**
 * A parsed path object generated by path.parse() or consumed by path.format().
 */
interface ParsedPath {
  /**
   * The root of the path such as '/' or 'c:\'
   */
  root: string
  /**
   * The full directory path such as '/home/user/dir' or 'c:\path\dir'
   */
  dir: string
  /**
   * The file name including extension (if any) such as 'index.html'
   */
  base: string
  /**
   * The file extension (if any) such as '.html'
   */
  ext: string
  /**
   * The file name without extension (if any) such as 'index'
   */
  name: string
}

// root：路径所属的根盘符。
// dir：路径所属的文件夹。
// base：路径对应的文件名。
// ext：路径对应文件的扩展名。
// name：文件对应的文件名称（不包含扩展名）​。
